tasks/urls.py
from django.urls import path

from tasks.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView,
    TaskCompletedView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="home"),
    path("task/create/", TaskCreateView.as_view(), name="task_create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task_update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
    path(
        "task/<int:pk>/task_completed/",
        TaskCompletedView.as_view(),
        name="task-completed",
    ),
    path("tag/", TagListView.as_view(), name="tag_list"),
    path("tag/create/", TagCreateView.as_view(), name="tag_create"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag_update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
]


app_name = "tasks"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
]

tasks/models.py
from django.db import models
from django.utils.timezone import now


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True, default=now)
    is_completed = models.BooleanField(default=False)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name="tags")

    def __str__(self):
        return f"{self.content} {self.is_completed}"

tasks/views.py
from django.db.models import F
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from tasks.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "tasks/task_list.html"
    context_object_name = "task_list"
    queryset = Task.objects.all().order_by(F("is_completed"), "-created_time")


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:home")
    template_name = "tasks/task_form.html"


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:home")
    template_name = "tasks/task_form.html"


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:home")
    template_name = "tasks/task_confirm_delete.html"


class TaskCompletedView(generic.View):
    model = Task
    fields = ("is_completed",)

    def post(self, request, pk):
        task = Task.objects.get(id=pk)

        task.is_completed = not task.is_completed
        task.save()

        return redirect("tasks:home")


class TagListView(generic.ListView):
    model = Tag
    template_name = "tasks/tag_list.html"
    context_object_name = "tag_list"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag_list")
    template_name = "tasks/tag_form.html"


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag_list")
    template_name = "tasks/tag_form.html"


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag_list")
    template_name = "tasks/tag_confirm_delete.html"

templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
  {% block title %}
      <title>Library</title>
  {% endblock %}
  <meta charset="utf=8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        {% block sidebar %}
            {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>
      <div class="col-sm-9">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'tasks:home' %}">Home</a></li>
  <li class="list-group-item"><a href='{% url 'tasks:tag_list' %}'>Tags</a></li>
</ul>

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete tag?</h1>

<p>Are you sure you want to delete the tag: {{ tag }}</p>
<p><i>All tasks with this tag will be also deleted!</i></p>


<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger" />
</form>

{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create"}} Tag</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy}}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Tags
  <a href="{% url 'tasks:tag_create' %}" class="btn btn-primary">Add Tag</a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
          <tr>
            <td>
                <a href="#">{{ tag.name }}</a>
            </td>
            <td>
                <a href="{% url 'tasks:tag_update' pk=tag.id %}" class="btn btn-primary">Update</a>
            </td>
            <td>
                <a href="{% url 'tasks:tag_delete' pk=tag.id %}" class="btn btn-danger">Delete</a>
            </td>
          </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no books in library</p>
  {% endif %}
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete task?</h1>

<p>Are you sure you want to delete the task: {{ task }}</p>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger" />
</form>

{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create"}} Task</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy}}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>TODO list
  <a href="{% url 'tasks:task_create' %}" class="btn btn-primary">Add task</a>
  </h1>

  {% if task_list %}
      {% for task in task_list %}
        <h3>{{ task.content }}
          {% if task.is_completed %}
            <div style="display: flex; justify-content: space-between;">
              <span style="color: green">Done</span>
                <form method="post" action="{% url 'tasks:task-completed' pk=task.id %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-secondary">Undo</button>
                </form>
            </div>
            {% else %}
            <div style="display: flex; justify-content: space-between;">
              <span style="color: red">Not done</span>
              <form method="post" action="{% url 'tasks:task-completed' pk=task.id %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-success">Complete</button>
              </form>
            </div>
          {% endif %}
        </h3>
          <p><strong>Created:</strong> {{ task.created_time }} {% if task.deadline is not None %}<strong>Deadline:</strong>{{ task.deadline }}{% endif %}</p>
        <h5>Tags: {{ task.tag.name }} <a href="{% url 'tasks:task_update' pk=task.id %}" class="btn btn-primary">Update</a> <a href="{% url 'tasks:task_delete' pk=task.id %}" class="btn btn-danger">Delete</a></h5>
        <br>
      {% endfor %}
  {% else %}
    <p>There are no tasks</p>
  {% endif %}
{% endblock %}